title: DPACHECO
description: Networking - Ciberseguridad
theme: just-the-docs

url: https://just-the-docs.github.io
color_scheme: dark
baseurl: "/docs"

# A침adir una secci칩n de defaults para las p치ginas
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      order: 1  # A침adir un orden predeterminado si es necesario
